//+------------------------------------------------------------------+
//| Constants.mqh                                                    |
//+------------------------------------------------------------------+
#ifndef __ORBVWAP_CONSTANTS_MQH__
#define __ORBVWAP_CONSTANTS_MQH__

#define ORBVWAP_LOG_PREFIX           "ORBVWAP"
#define ORBVWAP_DEFAULT_MAGIC        20260611
#define ORBVWAP_TRADE_COMMENT        "ORBVWAP"
#define ORBVWAP_JOURNAL_FILE         "ORBVWAP_journal.csv"
#define ORBVWAP_DECISIONS_FILE       "ORBVWAP_decisions.csv"
#define ORBVWAP_OUTCOMES_FILE        "ORBVWAP_outcomes.csv"
#define ORBVWAP_PATHS_FILE           "ORBVWAP_paths.csv"

#define ORBVWAP_REJECT_OUTSIDE_SESSION   "OUTSIDE_SESSION"
#define ORBVWAP_REJECT_ENTRY_CUTOFF      "ENTRY_CUTOFF"
#define ORBVWAP_REJECT_NY_ENTRY_DELAY      "NY_ENTRY_DELAY"
#define ORBVWAP_REJECT_LONDON_ENTRY_DELAY  "LONDON_ENTRY_DELAY"
#define ORBVWAP_REJECT_WEEKDAY_SKIP      "WEEKDAY_SKIP"
#define ORBVWAP_REJECT_RANGE_FORMING     "RANGE_FORMING"
#define ORBVWAP_REJECT_RANGE_TOO_NARROW  "RANGE_TOO_NARROW"
#define ORBVWAP_REJECT_VOL_INSUFFICIENT  "VOL_INSUFFICIENT"
#define ORBVWAP_REJECT_WRONG_SIDE_VWAP   "WRONG_SIDE_OF_VWAP"
#define ORBVWAP_REJECT_NO_BREAKOUT       "NO_BREAKOUT"
#define ORBVWAP_REJECT_STALE_BREAKOUT    "STALE_BREAKOUT"
#define ORBVWAP_REJECT_ALREADY_TRADED    "ALREADY_TRADED"
#define ORBVWAP_REJECT_SPREAD_TOO_HIGH   "SPREAD_TOO_HIGH"
#define ORBVWAP_REJECT_MAX_TRADES        "MAX_TRADES"
#define ORBVWAP_REJECT_COOLDOWN          "COOLDOWN"
#define ORBVWAP_REJECT_PERMISSION        "PERMISSION_DENIED"
#define ORBVWAP_REJECT_EQUITY_FLOOR      "EQUITY_FLOOR"
#define ORBVWAP_REJECT_STOPS_INVALID     "STOPS_INVALID"
#define ORBVWAP_REJECT_LOT_INVALID       "LOT_INVALID"
#define ORBVWAP_REJECT_MARGIN            "MARGIN_INSUFFICIENT"
#define ORBVWAP_REJECT_MIN_RR            "MIN_RR"
#define ORBVWAP_REJECT_D1_BIAS           "D1_BIAS"
#define ORBVWAP_REJECT_H4_STRUCTURE      "H4_STRUCTURE"
#define ORBVWAP_REJECT_ADX_FILTER        "ADX_FILTER"
#define ORBVWAP_REJECT_ATR_EXPANSION     "ATR_EXPANSION"
#define ORBVWAP_REJECT_SPREAD_RANGE      "SPREAD_RANGE"
#define ORBVWAP_REJECT_VOL_SPIKE         "VOL_SPIKE"
#define ORBVWAP_REJECT_VWAP_DISTANCE     "VWAP_DISTANCE"
#define ORBVWAP_REJECT_DAILY_LOSS        "DAILY_LOSS"
#define ORBVWAP_REJECT_CONSEC_LOSS       "CONSEC_LOSS_PAUSE"
#define ORBVWAP_REJECT_EQ_TRAIL          "EQ_TRAIL"

#endif // __ORBVWAP_CONSTANTS_MQH__
